USE [master]
GO


CREATE DATABASE [DBADB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBADB', FILENAME = N'C:\DBADB\DBADB.mdf' , SIZE = 161792KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBADB_log', FILENAME = N'C:\DBADB\DBADB_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBADB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBADB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBADB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBADB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBADB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBADB] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBADB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBADB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBADB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBADB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBADB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBADB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBADB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBADB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBADB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBADB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBADB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBADB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBADB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBADB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBADB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBADB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBADB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBADB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBADB] SET  MULTI_USER 
GO

ALTER DATABASE [DBADB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBADB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBADB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBADB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBADB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBADB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DBADB] SET QUERY_STORE = ON
GO

ALTER DATABASE [DBADB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [DBADB] SET  READ_WRITE 
GO


