USE [master]
GO

/****** Object:  Database [DBADB]    Script Date: 10/30/2025 11:33:39 AM ******/
CREATE DATABASE [DBADB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBADB', FILENAME = N'F:\MSSQL\DBADB\Data\DBADB.mdf' , SIZE = 187584KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DBADB_log', FILENAME = N'F:\MSSQL\DBADB\LOG\DBADB_log.ldf' , SIZE = 26816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBADB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBADB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBADB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBADB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBADB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBADB] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBADB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBADB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBADB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBADB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBADB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBADB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBADB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBADB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBADB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBADB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DBADB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBADB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBADB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBADB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBADB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBADB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBADB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBADB] SET RECOVERY FULL 
GO

ALTER DATABASE [DBADB] SET  MULTI_USER 
GO

ALTER DATABASE [DBADB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBADB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBADB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBADB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DBADB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBADB] SET  READ_WRITE 
GO


