USE [DBADB]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_RETENTION_LOGS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SourceTableName] [varchar](255) NULL,
	[DestinationTableName] [varchar](255) NULL,
	[TotalDataTransfered] [bigint] NULL,
	[Comment] [varchar](1000) NULL,
	[EntryDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBL_RETENTION_LOGS] ADD  DEFAULT (getdate()) FOR [EntryDate]
GO


